# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21be605829c7d9ab2d8f6cf7ff76c7e213d2b0d9ea9ea20df21ee34ab361518484269f09c6074229a126c34d3ec36901a987fc8905916396d6e2879239c101d3

test:
  secret_key_base: ff6d1872e4fa2d9d2cb889e88dbaea789763c89939ecd7d003617c4b521461e7820b787d3ef09a1a49c7a6a0d11861cf148a94325e02e78a38274fce132c3839

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
